# Generated by Django 5.0.7 on 2024-07-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_card_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('alt', models.CharField(max_length=100)),
            ],
        ),
    ]
