# Generated by Django 5.0.7 on 2024-07-27 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_carousels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carousels',
            new_name='Carousel',
        ),
    ]
