# Generated by Django 5.0.7 on 2024-07-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_rename_carousels_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='title',
            field=models.CharField(default='Carousel Title', max_length=50),
        ),
    ]
