# Generated by Django 5.0.7 on 2024-08-01 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_carousel_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
