# Generated by Django 5.0.8 on 2024-08-25 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlassClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('teacher', models.CharField(default='이소정', max_length=50)),
                ('category', models.CharField(default='One Day Class', max_length=50)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('discount_rate', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('image_url', models.URLField()),
                ('image_alt', models.CharField(max_length=50)),
                ('likes', models.IntegerField(default=0)),
                ('reviews', models.IntegerField(default=0)),
                ('total_rating', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0)),
                ('questions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('glass_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glass_class.glassclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
