# Generated by Django 5.0.7 on 2024-08-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlassClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('category', models.CharField(default='One Day Class', max_length=50)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('image_url', models.URLField()),
                ('image_alt', models.CharField(max_length=50)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('interests', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
