# Generated by Django 5.0.7 on 2024-08-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glass_class', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glassclass',
            name='teacher',
            field=models.CharField(default='이소정', max_length=50),
        ),
    ]
