# Generated by Django 5.0.8 on 2024-10-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glass_class', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
