# Generated by Django 5.0.8 on 2024-08-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glass_class', '0005_remove_glassclass_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glassclass',
            name='questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='glassclass',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='glassclass',
            name='total_rating',
            field=models.FloatField(default=0),
        ),
    ]
