# Generated by Django 5.0.8 on 2024-08-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glass_class', '0006_glassclass_questions_glassclass_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glassclass',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
