# Generated by Django 5.0.8 on 2024-08-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qna',
            name='glass_class',
        ),
        migrations.RemoveField(
            model_name='review',
            name='glass_class',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='QnA',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
