# Generated by Django 5.0.8 on 2024-09-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_detailinfo_product_like_product_question_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='content_rating',
            new_name='sub_rating_1',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='readiness_rating',
            new_name='sub_rating_2',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='teacher_rating',
            new_name='sub_rating_3',
        ),
    ]
