# Generated by Django 5.0.8 on 2024-09-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename_content_rating_review_sub_rating_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answerd_at',
        ),
        migrations.AddField(
            model_name='question',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
