# Generated by Django 5.0.8 on 2024-08-14 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_image_title_comment_qna_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
