# Generated by Django 5.0.8 on 2024-09-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_question_answerd_at_question_answered_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailinfo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='detailinfo',
            name='image_alt',
        ),
    ]
