# Generated by Django 5.0.8 on 2024-09-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_detailinfo_image_remove_detailinfo_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailinfo',
            name='description_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='description_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='description_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='image_url_1',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='image_url_2',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='image_url_3',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
