# Generated by Django 5.0.8 on 2024-09-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_detailinfo_description_1_detailinfo_description_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailinfo',
            old_name='image_url_1',
            new_name='product_image',
        ),
        migrations.RemoveField(
            model_name='detailinfo',
            name='image_url_2',
        ),
        migrations.RemoveField(
            model_name='detailinfo',
            name='image_url_3',
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='event_image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='notice_image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
