# Generated by Django 5.0.8 on 2024-09-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_rename_image_url_1_detailinfo_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailinfo',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
