# Generated by Django 5.0.8 on 2024-08-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_qna_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
