# Generated by Django 5.0.8 on 2024-08-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_qna_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='answerd_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
