# Generated by Django 5.0.8 on 2024-08-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_answer_image_comment_image_question_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
