# Generated by Django 5.0.8 on 2024-08-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_answer_image_alter_comment_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
