# Generated by Django 5.0.8 on 2024-08-20 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_delete_image'),
        ('glass_class', '0004_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.URLField(max_length=255)),
                ('image_alt', models.CharField(max_length=100)),
                ('glass_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glass_class.glassclass')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
