# Generated by Django 5.0.8 on 2024-09-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_phone_number_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_detail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='address_extra',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
