# Generated by Django 5.0.8 on 2024-09-11 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('discount_rate', models.IntegerField(default=0)),
                ('image_url', models.URLField()),
                ('image_alt', models.CharField(max_length=50)),
                ('likes', models.IntegerField(default=0)),
                ('reviews', models.IntegerField(default=0)),
                ('total_rating', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0)),
                ('questions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('purchased_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
