# Generated by Django 5.0.8 on 2024-09-16 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_purchased_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_1', models.TextField(blank=True, null=True)),
                ('description_2', models.TextField(blank=True, null=True)),
                ('description_3', models.TextField(blank=True, null=True)),
                ('image_url_1', models.URLField(blank=True, null=True)),
                ('image_url_2', models.URLField(blank=True, null=True)),
                ('image_url_3', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='detail_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.detail_info'),
        ),
    ]
