# Generated by Django 5.0.8 on 2024-09-17 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_detail_info_remove_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='detail_info',
        ),
        migrations.DeleteModel(
            name='Detail_Info',
        ),
    ]
