# .github/workflows/sonarcloud.yml

name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: read
  issues: write
  actions: write
  checks: write
  deployments: write
  statuses: write

env:
  PYTHON_VERSION: '3.12' # Python version to use
  POETRY_CACHE_DIR: '~/.cache/pypoetry'

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache Poetry and Virtualenv
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.POETRY_CACHE_DIR }}
            ./.venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Poetry를 사용해 의존성을 관리하므로 pip 대신 워크플로우에 poetry를 사용하도록 설정    
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo 'export PATH="$HOME/.local/bin:$PATH"' >> $GITHUB_ENV
          poetry --version

      - name: Setup virtualenv for Poetry
        run: |
          poetry config virtualenvs.in-project true

      - name: Install Dependencies
        run: |
          poetry install --no-root
      
      # SocarCloud를 사용해 정적 코드 분석을 수행하기 위해 SonarScanner를 다운로드하고 실분
      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}